# Generated by Django 6.0.7 on 2026-09-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bulkuploadjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price difference from the base product price. Can be positive or negative.', max_digits=10),
        ),
    ]
